### ISSUE TITLE
Entity ID expects URL, contradicting guidelines

### ISSUE THREAD

**Issue by pgchamberlin** [alphagov/verify-compliance-tool-gui#2]
The `/rp/id` form demands that the Entity ID is a URL, however the accompanying text states, "By convention entity IDs are URLs (although there's no technical reason why this needs to be the case)".

We should either not demand a URL or update the text appropriately.

<img width="922" alt="screen shot 2017-04-11 at 12 48 49" src="https://cloud.githubusercontent.com/assets/315467/24907767/6d656060-1eb5-11e7-9311-047211c80183.png">

**Comment by willp-bl** [comment]
We should demand an URL

**Comment by pgchamberlin** [comment]
Fixed by #3
