### ISSUE TITLE
Missing config example on completion of test setup

### ISSUE THREAD

**Issue by pgchamberlin** [alphagov/verify-compliance-tool-gui#4]
On page `/rp/success` we present the user with a TODO note where example config is promised. We should either take out the promise of config or do the TODO 😄 

<img width="1118" alt="screen shot 2017-04-11 at 13 16 53" src="https://cloud.githubusercontent.com/assets/315467/24908800/618f2448-1eb9-11e7-80c5-9aeeb8770319.png">

**Comment by vixus0** [comment]
We've currently removed the RP and MSA testing.
